version: '3.8'

services:
  backend:
    build:
      context: ./api_backend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./api_backend:/app
    environment:
      - FILE_NAME=data.xlsx

  frontend:
    build:
      context: ./chatbot_interface
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    volumes:
      - ./chatbot_interface:/chatbot_interface
    environment:
      - PANEL_SERVE_ADDRESS=0.0.0.0
      - PANEL_SERVE_PORT=8080
